<include href="public/header.phtml" />

<div class="row">
    <div class="medium-6 columns">
        <img src="/images/logoalt.png" alt="GSB Logo">
    </div>


</div>
<div class="white-panel fullwidth">

    <div class="row">
        <div class="medium-12 columns">
            <include href="public/messages.phtml" />
        </div>
    </div>
    <div class="row">
        <div class="medium-12 columns">
            <div class="row">
                <div class="medium-12 columns">
                    <div class="row">
                        <div class="medium-3 columns" style="border-right: 1px solid #dddddd;">
                            <include href="public/manager/partials/menu.phtml" />

                        </div>
                        <div class="medium-9 columns">
                            <div class="row">
                                <div class="col-md-12 columns">
                                    <h3>Mes fiches de frais</h3>

                                    <h4>Mois à afficher :</h4>



                                            <div class="col-md-12 columns">
                                                <label>
                                                    <select name="month">
                                                        <repeat group="{{ @ficheList }}" value="{{ @fiche }}">
                                                            <option value="{{ @fiche->mois }}">{{ @fiche->mois }}</option>
                                                        </repeat>
                                                    </select>
                                                </label>
                                            </div>


                                        <div class="col-md-12 columns text-right">
                                            <button class="button success changeMonth" type="button" placeholder=""><i class="fi-check"></i> Sélectionner</button>
                                        </div>
                                    <check if="{{ @ficheFrais }}">
                                        <h4>Fiche de frais du mois {{ @ficheFrais->fiche['mois'] }} :</h4>
                                        <table>
                                            <tbody>
                                                <tr>
                                                    <td>Etat : </td>
                                                    <td>{{ @ficheFrais->fiche['libelle'] }} {{ @ficheFrais->fiche['dateModif'] }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Montant validé : </td>
                                                    <td>{{ @ficheFrais->fiche['montantValide'] }}€</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <h5>Frais forfaitisés - {{ @ficheFrais->fiche['nbJustificatifs'] }} justificatifs reçus</h5>
                                        <table>
                                            <tbody>
                                                <repeat group="{{ @ficheFrais->bundled }}" value="{{ @ligne }}">
                                                    <tr>
                                                        <td>{{ @ligne['libelle'] }}</td>
                                                        <td>{{ @ligne['quantite'] }}</td>
                                                    </tr>
                                                </repeat>
                                            </tbody>
                                        </table>
                                        <h5>Frais hors forfait</h5>
                                        <table class="hover">
                                            <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Libellé</th>
                                                <th>Montant</th>
                                                <th></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <repeat group="{{ @ficheFrais->notBundled }}" value="{{ @ligne }}">
                                                <tr>
                                                    <td>{{ date_format(date_create(@ligne['date']), 'd/m/Y') }}</td>
                                                    <td>{{ @ligne['libelle'] }}</td>
                                                    <td>{{ @ligne['montant'] }}€</td>
                                                </tr>
                                            </repeat>

                                            </tbody>
                                        </table>
                                    </check>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<include href="public/footer.phtml" />
