<include href="public/header.phtml" />

    <div class="row">
        <div class="medium-6 columns">
            <img src="images/logoalt.png" alt="GSB Logo">
        </div>


    </div>

    <div class="white-panel fullwidth">

        <div class="row">
            <div class="medium-12 columns">
                <include href="public/messages.phtml" />
            </div>

        </div>



        <div class="row">
            <div class="medium-12 columns">
                <div class="row">
                    <div class="medium-12 columns">
                        <div class="row">
                            <div class="medium-3 columns">
                                <include href="public/manager/partials/menu.phtml" />

                            </div>
                            <div class="medium-9 columns">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<include href="public/footer.phtml" />
