<include href="public/header.phtml" />

    <div class="row">
        <div class="medium-10 medium-centered columns text-center">
            <img src="images/logo.png" alt="GSB Logo">
        </div>
    </div>
    <div class="white-panel fullwidth">

        <div class="row">
            <div class="medium-4 medium-centered columns">
                <include href="public/messages.phtml" />
            </div>
        </div>



        <div class="row">
            <div class="medium-4 medium-centered columns">
                    <div class="row">
                        <div class="col-md-12 columns">
                            <form method="POST" action="" autocomplete="off">
                                <!-- Empêche l'autocompletion de chrome -->
                                <input style="display:none">
                                <input type="password" style="display:none">
                                <!-- Fin empêche l'autocompletion de chrome -->
                                <div class="row">
                                    <div class="medium-12 columns">
                                        <input type="text" name="username" placeholder="Nom d'utilisateur" />
                                    </div>

                                    <div class="large-12 columns">
                                        <input type="password" name="password" placeholder="Mot de passe" />
                                    </div>
                                    <div class="medium-12 medium-centered columns">
                                        <input type="submit" class="button expanded" value="Connexion"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
<include href="public/footer.phtml" />