        <footer>
            <p class="text-center">&copy; 2016 - GSB</p>
        </footer>

        <script src="/bower_components/jquery/dist/jquery.js"></script>
        <script src="/bower_components/what-input/what-input.js"></script>
        <script src="/bower_components/foundation-sites/dist/foundation.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/dataTables.foundation.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/fixedheader/3.1.1/js/dataTables.fixedHeader.min.js"></script>
        <script src="/js/app.js"></script>

            <check if="{{  @application['environment'] == developpement }}">
                {{ @debugbarjs->render() }}
            </check>



    </body>
</html>